var upgradeDictDefault = {
    0: {Name: "Nahida",      Row:-1,  "Level": 1, "Cost":20, Factor:1,        Purchased: -1,   Type: "Catalyst",   Ele: "Dendro"          },
    1: {Name: "Traveller",   Row:-1,          Purchased: -1,   Type: "Sword",      Ele: "Any"                                             },
    2: {Name: "Collei",      Row:-1,          Purchased: -1,   Type: "Bow",        Ele: "Dendro"                                             },
    3: {Name: "Tighnari",    Row:-1,          Purchased: -1,   Type: "Bow",      Ele: "Dendro"                                             },
    4: {Name: "Candace",     Row:-1,          Purchased: -1,   Type: "Polearm",   Ele: "Hydro"                                             },
    5: {Name: "Dori",        Row:-1,          Purchased: -1,  Type: "Claymore",   Ele: "Electro"                                             },
    6: {Name: "Cyno",        Row:-1,          Purchased: -1,   Type: "Polearm",   Ele: "Electro"                                             },
    7: {Name: "Nilou",       Row:-1,          Purchased: -1,   Type: "Sword",     Ele: "Hydro"                                             },
    8: {Name: "Layla",       Row:-1,          Purchased: -1,   Type: "Sword",     Ele: "Cryo"                                             },
    9: {Name: "Faruzan",     Row:-1,          Purchased: -1,   Type: "Bow",       Ele: "Anemo"                                             },
    10: {Name: "Alhaitham",  Row:-1,          Purchased: -1,   Type: "Sword",    Ele: "Dendro"                                             },
    11: {Name: "Amber",      Row:-1,          Purchased: -1,   Type: "Bow",      Ele: "Pyro"                                             },
    12: {Name: "Bennett",    Row:-1,          Purchased: -1,   Type: "Sword",      Ele: "Pyro"                                             },
    13: {Name: "Noelle",     Row:-1,          Purchased: -1,   Type: "Claymore",      Ele: "Geo"                                             },
    14: {Name: "Barbara",    Row:-1,          Purchased: -1,   Type: "Catalyst",      Ele: "Hydro"                                             },
    15: {Name: "Lisa",       Row:-1,          Purchased: -1,   Type: "Catalyst",      Ele: "Electro"                                             },
    16: {Name: "Kaeya",      Row:-1,          Purchased: -1,   Type: "Sword",      Ele: "Cryo"                                             },
    17: {Name: "Diluc",      Row:-1,          Purchased: -1,   Type: "Claymore",      Ele: "Pyro"                                             },
    18: {Name: "Diona",      Row:-1,            Purchased: -1,   Type: "Bow",      Ele: "Cryo"                                             },
    19: {Name: "Fischl",     Row:-1,            Purchased: -1,   Type: "Bow",      Ele: "Electro"                                             },
    20: {Name: "Mona",       Row:-1,            Purchased: -1,   Type: "Catalyst",      Ele: "Hydro"                                             },
    21: {Name: "Rosaria",    Row:-1,            Purchased: -1,   Type: "Polearm",      Ele: "Cryo"                                             },
    22: {Name: "Klee",       Row:-1,            Purchased: -1,   Type: "Catalyst",      Ele: "Pyro"                                             },
    23: {Name: "Razor",      Row:-1,            Purchased: -1,   Type: "Claymore",      Ele: "Electro"                                             },
    24: {Name: "Sucrose",    Row:-1,            Purchased: -1,   Type: "Catalyst",      Ele: "Anemo"                                             },
    25: {Name: "Xiangling",  Row:-1,            Purchased: -1,   Type: "Polearm",      Ele: "Pyro"                                             },
    26: {Name: "Xingqiu",    Row:-1,            Purchased: -1,   Type: "Sword",      Ele: "Hydro"                                             },
    27: {Name: "Chongyun",   Row:-1,            Purchased: -1,   Type: "Claymore",      Ele: "Cryo"                                             },
    28: {Name: "Yaoyao",     Row:-1,            Purchased: -1,     Type: "Polearm",       Ele: "Dendro"                                             },
    29: {Name: "Xinyan",     Row:-1,            Purchased: -1,   Type: "Claymore",      Ele: "Pyro"                                             },
    30: {Name: "Yun Jin",    Row:-1,            Purchased: -1,   Type: "Polearm",      Ele: "Geo"                                             },
    31: {Name: "Beidou",     Row:-1,            Purchased: -1,   Type: "Claymore",      Ele: "Electro"                                             },
    32: {Name: "Ningguang",  Row:-1,            Purchased: -1,   Type: "Catalyst",      Ele: "Geo"                                             },
    33: {Name: "Ganyu",      Row:-1,            Purchased: -1,   Type: "Bow",      Ele: "Cryo"                                             },
    34: {Name: "Keqing",     Row:-1,            Purchased: -1,   Type: "Sword",      Ele: "Electro"                                             },
    35: {Name: "Yanfei",     Row:-1,            Purchased: -1,   Type: "Catalyst",      Ele: "Pyro"                                             },
    36: {Name: "Kazuha",     Row:-1,            Purchased: -1,   Type: "Sword",      Ele: "Anemo"                                             },
    37: {Name: "Thoma",      Row:-1,            Purchased: -1,   Type: "Polearm",      Ele: "Pyro"                                             },
    38: {Name: "Yoimiya",    Row:-1,            Purchased: -1,   Type: "Bow",      Ele: "Pyro"                                             },
    39: {Name: "Ayaka",      Row:-1,            Purchased: -1,   Type: "Sword",      Ele: "Cryo"                                             },
    40: {Name: "Gorou",      Row:-1,            Purchased: -1,   Type: "Bow",      Ele: "Geo"                                             },
    41: {Name: "Kokomi",     Row:-1,            Purchased: -1,   Type: "Catalyst",      Ele: "Hydro"                                             },
    42: {Name: "Sayu",       Row:-1,            Purchased: -1,   Type: "Claymore",      Ele: "Anemo"                                             },
    43: {Name: "Heizou",     Row:-1,            Purchased: -1,   Type: "Catalyst",      Ele: "Anemo"                                             },
    44: {Name: "Shinobu",    Row:-1,            Purchased: -1,   Type: "Sword",      Ele: "Electro"                                             },
    45: {Name: "Itto",       Row:-1,            Purchased: -1,   Type: "Claymore",      Ele: "Geo"                                             },
    46: {Name: "Sara",       Row:-1,            Purchased: -1,   Type: "Bow",      Ele: "Electro"                                             },
    47: {Name: "Venti",      Row:-1,           Purchased: -1,   Type: "Bow",   Ele: "Anemo"                                             },
    48: {Name: "Zhongli",    Row:-1,           Purchased: -1,   Type: "Polearm",   Ele: "Geo"                                             },
    49: {Name: "Raiden",     Row:-1,            Purchased: -1,   Type: "Polearm",   Ele: "Electro"                                             },
// RMB TO UPDATE MAX CONSTANTS// RMB TO UPDATE MAX CONSTANTS// RMB TO UPDATE MAX CONSTANTS// RMB TO UPDATE MAX CONSTANTS// RMB TO UPDATE MAX CONSTANTS
    100: {Name: "Jean",        Row:-1,        "Level": 0, Purchased: -10,   Type: "Sword",   Ele: "Anemo"                                             },
    101: {Name: "Albedo",      Row:-1,        "Level": 0, Purchased: -10,   Type: "Sword",   Ele: "Geo"                                             },
    102: {Name: "Qiqi",        Row:-1,        "Level": 0, Purchased: -10,   Type: "Sword",   Ele: "Cryo"                                             },
    103: {Name: "Yelan",       Row:-1,        "Level": 0, Purchased: -10,   Type: "Bow",   Ele: "Hydro"                                             },
    104: {Name: "Shenhe",      Row:-1,        "Level": 0, Purchased: -10,   Type: "Polearm",   Ele: "Cryo"                                             },
    105: {Name: "Ayato",       Row:-1,        "Level": 0, Purchased: -10,   Type: "Sword",   Ele: "Hydro"                                             },
    106: {Name: "Yae Miko",    Row:-1,        "Level": 0, Purchased: -10,   Type: "Catalyst",   Ele: "Electro"                                             },
    107: {Name: "Eula",        Row:-1,        "Level": 0, Purchased: -10,   Type: "Claymore",   Ele: "Cryo"                                             },
    108: {Name: "Hu Tao",      Row:-1,        "Level": 0, Purchased: -10,   Type: "Polearm",   Ele: "Pyro"                                             },
    109: {Name: "Xiao",        Row:-1,        "Level": 0, Purchased: -10,   Type: "Polearm",   Ele: "Anemo"                                             },
    110: {Name: "Tartaglia",   Row:-1,        "Level": 0, Purchased: -10,   Type: "Bow",   Ele: "Hydro"                                             },
    111: {Name: "Scaramouche", Row:-1,        "Level": 0, Purchased: -10,   Type: "Catalyst",   Ele: "Anemo"                                             },
    112: {Name: "Dehya",      Row:-1,         "Level": 0, Purchased: -10,  Type: "Claymore",   Ele: "Pyro"                                             },
};

// RMB TO UPDATE MAX CONSTANTS
var Inventory = {
    1001: {Name:"coolSteel",      Star:3,  Type:"Sword"                                             },
    1002: {Name:"ferrous",        Star:3,  Type:"Claymore"                                             },
    1003: {Name:"mappa",          Star:4,  Type:"Catalyst"                                             },
    1004: {Name:"rust",           Star:4,  Type:"Bow"                                             },
    1005: {Name:"silverSword",    Star:2,  Type:"Sword"                                             },
    1006: {Name:"dullSword",      Star:1,  Type:"Sword"                                             },
    1007: {Name:"skywardBlade",   Star:5,  Type:"Sword"                                             },
    1008: {Name:"harbingerDawn",  Star:3,  Type:"Sword"                                             },
    1009: {Name:"travelerHandySword",      Star:3,  Type:"Sword"                                             },
    1010: {Name:"sacSword",          Star:3,  Type:"Sword"                                             },
    1011: {Name:"lionsRoar",           Star:3,  Type:"Sword"                                             },
    1012: {Name:"aquilaFavonia",           Star:5,  Type:"Sword"                                             },
// RMB TO UPDATE MAX CONSTANTS
// RMB TO UPDATE MAX CONSTANTS
// RMB TO UPDATE MAX CONSTANTS
// RMB TO UPDATE MAX CONSTANTS
// RMB TO UPDATE MAX CONSTANTS
    2001: {Name:"gladiator",      Star:4},
    2002: {Name:"deepwood",       Star:5},
    2003: {Name:"crimWitch",      Star:5},
// RMB TO UPDATE MAX CONSTANTS
    3001: {Name:"masalaCheese",   Star:2,                     BuffTemp:10},
    3002: {Name:"jueyunchili",    Star:2,                     BuffTemp:10},

    4001: {Name:"wandererEXP",    Star:2,                     BuffLvl:1},
    4002: {Name:"adventureEXP",   Star:3,                     BuffLvl:5},
    4003: {Name:"heroEXP",        Star:4,                     BuffLvl:10},
};

var tooltip = {
    Nahida:{name:"Nahida", lore:"A caged bird secluded within the confines of the Sanctuary of Surasthana who can only see the world in her dreams."},
    Traveller:{name:"The Traveller", lore:"The keeper is fading away; the creator has not yet come.But the world shall burn no more, for you shall ascend."},
    Collei:{name:"             Collei               ", lore:""               },
    Cyno:{name:"               Cyno               ", lore:""                 },
    Candace:{name:"            Candace               ", lore:""            },
    Dori:{name:"               Dori               ", lore:""                 },
    Tighnari:{name:"           Tighnari               ", lore:""           },
    Nilou:{name:"              Nilou               ", lore:""              },
    Layla:{name:"              Layla               ", lore:""             },
    Faruzan:{name:"            Faruzan               ", lore:""            },
    Dehya:{name:"              Dehya               ", lore:""             },
    Alhaitham:{name:"           Alhaitham               ", lore:""         },
    Amber:{name:"              Amber               ", lore:""           },
    Bennett:{name:"            Bennett               ", lore:""           },
    Noelle:{name:"             Noelle               ", lore:""              },
    Barbara:{name:"            Barbara               ", lore:""               },
    Lisa:{name:"               Lisa               ", lore:""                    },
    Kaeya:{name:"              Kaeya               ", lore:""             },
    Diluc:{name:"              Diluc               ", lore:""                },
    Diona:{name:"              Diona               ", lore:""             },
    Fischl:{name:"             Fischl von Luftschloss Narfidort               ", lore:""               },
    Mona:{name:"               Mona               ", lore:""                    },
    Rosaria:{name:"            Rosaria               ", lore:""               },
    Klee:{name:"               Klee               ", lore:""                   },
    Razor:{name:"              Razor               ", lore:""                     },
    Sucrose:{name:"            Sucrose               ", lore:""                 },
    Xiangling:{name:"           Xiangling               ", lore:""             },
    Xingqiu:{name:"            Xingqiu               ", lore:""              },
    Chongyun:{name:"           Chongyun               ", lore:""               },
    Yaoyao:{name:"             Yaoyao               ", lore:""                    },
    Xinyan:{name:"             Xinyan               ", lore:""                 },
    "Yun Jin":{name:"           Yun Jin               ", lore:""              },
    Beidou:{name:"             Beidou               ", lore:""                    },
    Ningguang:{name:"           Ningguang               ", lore:""             },
    Ganyu:{name:"              Ganyu               ", lore:""             },
    Keqing:{name:"             Keqing               ", lore:""                 },
    Yanfei:{name:"             Yanfei               ", lore:""                 },
    Kazuha:{name:"             Kaedehara Kazuha               ", lore:""               },
    Thoma:{name:"              Thoma               ", lore:""                 },
    Yoimiya:{name:"            Yoimiya               ", lore:""           },
    Ayaka:{name:"              Kamisato Ayaka               ", lore:""               },
    Gorou:{name:"              Gorou               ", lore:""            },
    Kokomi:{name:"             Sangonomiya Kokomi               ", lore:""                  },
    Sayu:{name:"               Sayu               ", lore:""                    },
    Heizou:{name:"             Shikanoin Heizou               ", lore:""                  },
    Shinobu:{name:"            Kuki Shinobu               ", lore:""                },
    Itto:{name:"               Arataki Itto               ", lore:""                  },
    Sara:{name:"               Kujou Sara               ", lore:""                 },
    Venti:{name:"              Venti               ", lore:""          },
    Zhongli:{name:"            Zhongli               ", lore:""          },
    Raiden:{name:"             Raiden Shogun              ", lore:""                },
    Jean:{name:"               Jean               ", lore:""},
    Albedo:{name:"             Albedo               ", lore:""}        ,
    Qiqi:{name:"               Qiqi               ", lore:""}           ,
    Yelan:{name:"              Yelan               ", lore:""}         ,
    Shenhe:{name:"             Shenhe               ", lore:""}           ,
    Ayato:{name:"              Kamisato Ayato               ", lore:""}           ,
    "Yae Miko":{name:"           Yae Miko               ", lore:""}             ,
    Eula:{name:"               Eula               ", lore:""}              ,
    "Hu Tao":{name:"           Hu Tao               ", lore:""}           ,
    Xiao:{name:"               Xiao               ", lore:""}              ,
    Tartaglia:{name:"           Tartaglia               ", lore:""}        ,
    Scaramouche:{name:"           Scaramouche               ", lore:""}        ,
    // ^^^ CHARACTERS ^^^ | vvv ITEMS vvv 
    coolSteel:{name:"", lore:""},               
    ferrous:{name:"", lore:""},               
    mappa:{name:"", lore:""},               
    rust:{name:"", lore:""},               
    silverSword:{name:"", lore:""},               
    dullSword:{name:"", lore:""},               
    skywardBlade:{name:"", lore:""},               
    harbingerDawn:{name:"", lore:""},               
    travelerHandySword:{name:"", lore:""},               
    sacSword:{name:"", lore:""},               
    lionsRoar:{name:"", lore:""},               
    aquilaFavonia:{name:"", lore:""},               

    gladiator:{name:"", lore:""},               
    deepwood:{name:"", lore:""},               
    crimWitch:{name:"", lore:""},               

    masalaCheese:{name:"", lore:""},               
    jueyunchili:{name:"", lore:""},               

    wandererEXP:{name:"", lore:""},               
    adventureEXP:{name:"", lore:""},               
    heroEXP:{name:"", lore:""},               
};

var expeditionDict = {
    1:{Text:"Explore Teyvat | 100 "                 ,Locked:"0" ,Lore:"The best way to understand the world is to explore all that is around you, leaving no stone unturned. Solving the enigmas of old, helping hapless travelers, and following the trails of long-lost treasure will all become invaluable knowledge and experience."},
    2:{Text:"Visit the Adventurers' Guild | 250 "   ,Locked:"0" ,Lore:"They boldly venture up to the stars, down to the abyss, or so their motto would have you believe. In truth, they take on jobs ranging from finding kittens to exploring domains."},
    3:{Text:"Challenge Domains | 500 "              ,Locked:"1" ,Lore:"Domains hide precious treasures. Be sure to explore the domains scattered all over the world to find the treasures hidden within."},
    4:{Text:"Hunt Boss Enemies | 750 "              ,Locked:"1" ,Lore:"Bosses are strong Enemies that are scattered across the world. They are much stronger than elite enemies, but also provide luxurious rewards for defeating them."},
    5:{Text:"Abyss Diving | 1000 "                   ,Locked:"1" ,Lore:"Monsters and humans alike flock to the tower in search of the secrets and treasures it contains. Challenge different floors of the tower and defeat the enemies within to win Abyssal Stars...with the help of an ally."},
    6:{Text:"Locked"                         ,Locked:"0" ,Lore:"Perhaps this path will open after some time..."            },
    7:{Text:""                               ,Locked:"0" ,Lore:""            },
}

var achievementList = {
    1: {Name:"Nut Collector",       Description:"Collect 10 nuts"                   ,"Done": false            },
    2: {Name:"Fan of Nuts",             Description:"Collect 1000 nuts"                  ,"Done": false            },
    3: {Name:"Nut Gatherer",        Description:"Collect 10,000 nuts"               ,"Done": false            },
    4: {Name:"Nut Accumulator",     Description:"Collect 1 million nuts"            ,"Done": false            },
    5: {Name:"Nut Hobbyist",        Description:"Collect 100 million nuts"          ,"Done": false            },
    6: {Name:"Nut Addict",          Description:"Collect 1 billion nuts"            ,"Done": false            },
    7: {Name:"Nut Fancier",         Description:"Collect 100 billion nuts"          ,"Done": false            },
    8: {Name:"Lord of the Nuts",            Description:"Collect 1 trillion nuts"           ,"Done": false            },
    9: {Name:"Nut Authority",       Description:"Collect 100 trillion nuts"         ,"Done": false            },
    10: {Name:"Nut Connoisseur",    Description:"Collect 1 quadrillion nuts"        ,"Done": false            },
    11: {Name:"Devotee of Nuts",        Description:"Collect 100 quadrillion nuts"      ,"Done": false            },
    12: {Name:"Aficionado of Nuts",     Description:"Collect 1 quintillion nuts"        ,"Done": false            },
    13: {Name:"Nut Pundit",         Description:"Collect 100 quintillion nuts"      ,"Done": false            },
    14: {Name:"Nut Antiquarian",    Description:"Collect 1 sextillion nuts"         ,"Done": false            },
    15: {Name:"Nut Savant",         Description:"Collect 100 sextillion nuts"       ,"Done": false            },
    16: {Name:"Nut Archon",         Description:"Collect 1 septillion nuts"         ,"Done": false            },
    101: {Name:"",                  Description:"Reach 1 NpS"                       ,"Done": false            },
    102: {Name:"",                  Description:"Reach 10 NpS"                      ,"Done": false            },
    103: {Name:"",                  Description:"Reach 100 NpS"                     ,"Done": false            },
    104: {Name:"",                  Description:"Reach 10,000 NpS"                  ,"Done": false            },
    105: {Name:"",                  Description:"Reach 100,000 NpS"                 ,"Done": false            },
    106: {Name:"",                  Description:"Reach 1 million NpS"               ,"Done": false            },
    107: {Name:"",                  Description:"Reach 100 million NpS"             ,"Done": false            },
    108: {Name:"",                  Description:"Reach 1 billion NpS"               ,"Done": false            },
    109: {Name:"",                  Description:"Reach 100 billion NpS"             ,"Done": false            },
    110: {Name:"",                  Description:"Reach 1 trillion NpS"              ,"Done": false            },
    111: {Name:"",                  Description:"Reach 100 trillion NpS"            ,"Done": false            },
    112: {Name:"",                  Description:"Reach 1 quadrillion NpS"           ,"Done": false            },
    113: {Name:"",                  Description:"Reach 100 quadrillion NpS"         ,"Done": false            },
    114: {Name:"",                  Description:"Reach 1 quintillion NpS"           ,"Done": false            },
    115: {Name:"",                  Description:"Reach 100 quintillion NpS"         ,"Done": false            },
    116: {Name:"Champion of Tevyat",Description:"Reach 1 sextillion NpS"            ,"Done": false            },
    201: {Name:"",                  Description:"Click 100 times"                   ,"Done": false            },
    202: {Name:"",                  Description:"Click 1000 times"                  ,"Done": false            },
    203: {Name:"",                  Description:"Click 10,000 times"                ,"Done": false            },
    204: {Name:"",                  Description:"Click 100,000 times"               ,"Done": false            },
    205: {Name:"Master of Cultivation",Description:"Click 1 million times"             ,"Done": false            },
    301: {Name:"",                     Description:"Upgrade characters 1 time"         ,"Done": false            },
    302: {Name:"",                     Description:"Upgrade characters 10 time"        ,"Done": false            },
    303: {Name:"",                     Description:"Upgrade characters 100 time"       ,"Done": false            },
    304: {Name:"",                     Description:"Upgrade characters 1000 time"      ,"Done": false            },
    305: {Name:"Heart of Dendro ",     Description:"Upgrade characters 10,000 time"    ,"Done": false            },
    401: {Name:"",                     Description:""                                  ,"Done": false            },
    402: {Name:"",                     Description:""                                  ,"Done": false            },
    403: {Name:"",                     Description:""                                  ,"Done": false            },
    404: {Name:"",                     Description:""                                  ,"Done": false            },
    405: {Name:"",                     Description:""                                  ,"Done": false            },
    406: {Name:"Golden Nut",           Description:""                                  ,"Done": false            },
    407: {Name:"",                     Description:""                                  ,"Done": false            },
    408: {Name:"",                     Description:""                                  ,"Done": false            },
}

export { upgradeDictDefault,tooltip,Inventory,expeditionDict,achievementList };