tooltip = {
"Nahida"    :{text:"A caged bird secluded within the confines of the Sanctuary of Surasthana who can only see the world in her dreams."},
"Traveller" :{text:""},
"Collei"    :{text:""},
"Cyno"      :{text:""},
"Candace"   :{text:""},
"Dori"      :{text:""},
"Tighnari"  :{text:""},
"Nilou"     :{text:""},
"Layla"     :{text:""},
"Faruzan"   :{text:""},
"Dehya"     :{text:""},
"Alhaitham" :{text:""},
"Amber"     :{text:""},
"Bennett"   :{text:""},
"Noelle"    :{text:""},
"Barbara"   :{text:""},
"Lisa"      :{text:""},
"Kaeya"     :{text:""},
"Diluc"     :{text:""},
"Diona"     :{text:""},
"Fischl"    :{text:""},
"Mona"      :{text:""},
"Rosaria"   :{text:""},
"Klee"      :{text:""},
"Razor"     :{text:""},
"Sucrose"   :{text:""},
"Xiangling" :{text:""},
"Xingqiu"   :{text:""},
"Chongyun"  :{text:""},
"Xinyan"    :{text:""},
"Yun Jin"   :{text:""},
"Beidou"    :{text:""},
"Ningguang" :{text:""},
"Ganyu"     :{text:""},
"Keqing"    :{text:""},
"Yanfei"    :{text:""},
"Kazuha"    :{text:""},
"Thoma"     :{text:""},
"Yoimiya"   :{text:""},
"Ayaka"     :{text:""},
"Gorou"     :{text:""},
"Kokomi"    :{text:""},
"Sayu"      :{text:""},
"Heizou"    :{text:""},
"Shinobu"   :{text:""},
"Itto"      :{text:""},
"Sara"      :{text:""},
"Venti"     :{text:""},
"Zhongli"   :{text:""},
"Raiden"    :{text:""},
"Jean"      :{text:""},
"Albedo"    :{text:""},
"Qiqi"      :{text:""},
"Yelan"     :{text:""},
"Shenhe"    :{text:""},
"Ayato"     :{text:""},
"Yae Miko"  :{text:""},
"Eula"      :{text:""},
"Hu Tao"    :{text:""},
"Xiao"      :{text:""},
"Tartaglia" :{text:""},
"Scaramouche":{text:""}, 
}